/**
 * Montagsmaler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DrawingData { 
    roomId: string;
    /**
     * Serialized Fabric.js path object
     */
    path: { [key: string]: any; };
    senderSessionId: string;
}

