/**
 * Montagsmaler API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DrawingDataFrom } from './drawingDataFrom';


export interface DrawingData { 
    roomId: string;
    senderSessionId: string;
    color: string;
    width: number;
    from: DrawingDataFrom;
    to: DrawingDataFrom;
}

