/**
 * Montagsmaler API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface GameSession { 
    roomId?: string;
    users?: Array<User>;
    readyStatus?: { [key: string]: boolean; };
    submittedWords?: { [key: string]: string; };
    drawingOrder?: Array<User>;
    currentDrawerIndex?: number;
    phase?: string;
    currentWord?: string;
    currentDrawer?: User;
    timerSeconds?: number;
}

