/**
 * Montagsmaler API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserUpdateResponse { 
    username?: string;
    email?: string;
    firstname?: string;
    lastname?: string;
    aboutMe?: string;
}

