/**
 * Montagsmaler API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    id?: string;
    username?: string;
    email?: string;
    firstName?: string;
    lastName?: string;
    aboutMe?: string;
    keycloakId?: string;
    gameWebSocketSessionId?: string;
}

