/**
 * Montagsmaler API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TokenResponse } from './tokenResponse';


export interface UserRegistrationResponse { 
    username?: string;
    email?: string;
    token?: TokenResponse;
}

